// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwaqkgxmpoxjjosdbjav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3YXFrZ3htcG94ampvc2RiamF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NTcxNjIsImV4cCI6MjA3MzQzMzE2Mn0.MqH8WbYPPIDGtgwoqo-9lFvIL8o7uNyOry5j7qxNvic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});